Fix for RNN R API
dmlc/dmlc.github.io pull request #45
Opened 2017-12-20 01:31 UTC by jeremiedb

Figures refresh following rework of the RNN R API.

2017-12-21 15:27 UTC, thirdwing commented
@hetong007

2017-12-21 17:25 UTC, hetong007 requested changes

2017-12-21 17:25 UTC, hetong007 commented on _posts/2017-10-11-rnn-bucket-mxnet-R.md
> +Below are the graph representations of a seq-to-one architecture with LSTM cells. Note that input data is of shape `seq.length X batch.size` while the RNN operator requires input of of shape `hidden.
one unnecessary "of" at
> requires input of *of* shape

2017-12-23 19:55 UTC, hetong007 approved these changes

2017-12-23 19:55 UTC, merged